name: internship
description: UI mock for location-based events
version: 1.0.0+1
publish_to: "none"
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geocoding: ^2.2.0
  cupertino_icons: ^1.0.6
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.2  # (optional, for real location later)

flutter:
  uses-material-design: true
  assets:
    - assets/events.json